#pragma once

#include <stdbool.h>
#include <stdint.h>

// MeteoAlarm warning zones (EMMA_ID) as simplified polygons; data generated by tools/gen_zones.py.

typedef struct {
    uint16_t first;   // index into WARN_PTS
    uint16_t count;
} warn_ring_t;

typedef struct {
    char code[6];            // "ES107"
    const char *name;        // "Ribera del Ebro de Zaragoza"
    uint16_t ring_first;
    uint16_t ring_count;
    int32_t bbox[4];         // min lon, min lat, max lon, max lat (1e-5 deg)
} warn_zone_t;

extern const warn_zone_t WARN_ZONES[];
extern const int WARN_ZONE_COUNT;
extern const warn_ring_t *WARN_RINGS;
extern const int32_t (*WARN_PTS)[2];

// Zones containing (lat, lon), written to `out` (indices into WARN_ZONES). Returns count.
int warn_zones_at(float lat, float lon, int *out, int max);
