#!/usr/bin/env python3
"""Generate main/services/warn_zones.c: simplified polygons of the Spanish MeteoAlarm
warning zones (EMMA_ID geocodes), so the device can find which zone(s) contain its location.

Source: MeteoAlarm geocodes file (CC BY 4.0), e.g.
  https://gitlab.com/meteoalarm-pm-group/documents/-/raw/master/MeteoAlarm_Geocodes_2026_07_31.json

Usage:  uvx --with shapely python tools/gen_zones.py <geocodes.json> [country=ES] [tolerance_deg=0.005]
"""
import json
import pathlib
import sys

from shapely.geometry import Point, shape

src = sys.argv[1]
country = sys.argv[2] if len(sys.argv) > 2 else "ES"
tol = float(sys.argv[3]) if len(sys.argv) > 3 else 0.005  # ~500 m

feats = [f for f in json.load(open(src))["features"]
         if f["properties"].get("type") == "EMMA_ID" and f["properties"]["code"].startswith(country)]
feats.sort(key=lambda f: f["properties"]["code"])

zones, rings, points = [], [], []
for f in feats:
    geom = shape(f["geometry"]).simplify(tol, preserve_topology=True)
    polys = [geom] if geom.geom_type == "Polygon" else list(geom.geoms)
    first = len(rings)
    for p in polys:
        for ring in [p.exterior, *p.interiors]:
            coords = list(ring.coords)[:-1]  # drop the closing point
            if len(coords) < 3:
                continue
            rings.append((len(points), len(coords)))
            points.extend((round(x * 1e5), round(y * 1e5)) for x, y in coords)
    minx, miny, maxx, maxy = geom.bounds
    zones.append((f["properties"]["code"], f["properties"]["name"], first, len(rings) - first,
                  [round(minx * 1e5), round(miny * 1e5), round(maxx * 1e5), round(maxy * 1e5)]))

# Sanity check: Zaragoza city must be in "Ribera del Ebro de Zaragoza".
if country == "ES":
    hit = [f["properties"]["code"] for f in feats if shape(f["geometry"]).contains(Point(-0.877, 41.656))]
    assert "ES107" in hit, hit

def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

out = pathlib.Path(__file__).resolve().parent.parent / "main" / "services" / "warn_zones.c"
L = [f"// Generated by tools/gen_zones.py from the MeteoAlarm geocodes (CC BY 4.0) — do not edit.",
     f"// {len(zones)} {country} zones, {len(rings)} rings, {len(points)} points, simplified at {tol} deg.",
     '#include "warn_zones.h"', "",
     "static const int32_t PTS[][2] = {  // lon, lat in 1e-5 degrees"]
L += ["    " + ", ".join(f"{{{x}, {y}}}" for x, y in points[i:i + 6]) + "," for i in range(0, len(points), 6)]
L += ["};", "", "static const warn_ring_t RINGS[] = {"]
L += ["    " + ", ".join(f"{{{s}, {n}}}" for s, n in rings[i:i + 8]) + "," for i in range(0, len(rings), 8)]
L += ["};", "", "const warn_zone_t WARN_ZONES[] = {"]
L += [f"    {{ \"{c}\", {cstr(n)}, {r0}, {rn}, {{ {b[0]}, {b[1]}, {b[2]}, {b[3]} }} }}," for c, n, r0, rn, b in zones]
L += ["};", "", "const int WARN_ZONE_COUNT = sizeof(WARN_ZONES) / sizeof(WARN_ZONES[0]);",
      "const warn_ring_t *WARN_RINGS = RINGS;", "const int32_t (*WARN_PTS)[2] = PTS;", ""]
out.write_text("\n".join(L))
print(f"wrote {out}: {len(zones)} zones, {len(rings)} rings, {len(points)} points (~{len(points) * 8 // 1024} KB)")
