#!/usr/bin/env python3
"""Render the Dacia "Link" emblem (2021 identity) to an LVGL A8 (alpha-only) image.

The outline is the single path from Wikimedia Commons "File:Dacia 2021 symbol.svg".
An A8 image is 1 byte/pixel and is tinted at runtime (image_recolor), so one bitmap
serves any colour. Trademark of Renault Group / Dacia: for this personal dashboard only.

Usage:  uvx --with cairosvg --with pillow python tools/gen_logo.py [width_px]
Writes: main/ui/dacia_logo.c
"""
import io
import pathlib
import sys

import cairosvg
from PIL import Image

PATH = (
    "m 0,0 v 12.29115 h 45.48833 v 6.19703 6.19743 h -45.48833 v 12.29114 h 50.22532 "
    "c 1.15207,0 1.9115,-0.3196 2.69672,-1.10909 l 13.22359,-12.8629 13.22399,12.8629 "
    "c 0.78522,0.7895 1.54465,1.10909 2.69672,1.10909 h 50.22532 v -12.29114 h -45.48872 "
    "v -6.19743 -6.19703 h 45.48872 v -12.29115 h -50.22532 c -1.15207,0 -1.9115,0.3196 "
    "-2.69672,1.10909 l -13.22399,12.86291 -13.22359,-12.86291 c -0.78522,-0.78949 "
    "-1.54465,-1.10909 -2.69672,-1.10909 z"
)
VIEW_W, VIEW_H = 132.29166, 36.97675

width = int(sys.argv[1]) if len(sys.argv) > 1 else 440
height = round(width * VIEW_H / VIEW_W)
svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VIEW_W} {VIEW_H}" '
       f'width="{width}" height="{height}"><path fill="#fff" d="{PATH}"/></svg>')
png = cairosvg.svg2png(bytestring=svg.encode(), output_width=width, output_height=height)
alpha = Image.open(io.BytesIO(png)).convert("RGBA").getchannel("A")
data = alpha.tobytes()

out = pathlib.Path(__file__).resolve().parent.parent / "main" / "ui" / "dacia_logo.c"
lines = [", ".join(f"0x{b:02x}" for b in data[i:i + 24]) for i in range(0, len(data), 24)]
out.write_text(f"""// Generated by tools/gen_logo.py — do not edit. Dacia "Link" emblem, A8 {width}x{height}.
#include "lvgl.h"

static const uint8_t dacia_logo_map[] = {{
    {(","+chr(10)+"    ").join(lines)}
}};

const lv_image_dsc_t dacia_logo = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_A8,
        .w = {width},
        .h = {height},
        .stride = {width},
    }},
    .data_size = sizeof(dacia_logo_map),
    .data = dacia_logo_map,
}};
""")
print(f"wrote {out} ({width}x{height}, {len(data)} bytes)")
